"""Make a test copy of the game with debug hooks.
Usage: python3 dev/make_debug.py index.html /tmp/dbg.html
Adds window.FREEZE (stops the real-time loop so tests can step frames by hand) and window.D (handles to game internals).
Never upload the debug copy; index.html must stay clean."""
import sys
s = open(sys.argv[1]).read()
s = s.replace("const dt = Math.max(0, Math.min(.05, (now - last) / 1000)); last = now;", "const dt = window.FREEZE ? 0 : Math.max(0, Math.min(.05, (now - last) / 1000)); last = now;", 1)
s = s.replace("renderer.setAnimationLoop(loop);", "renderer.setAnimationLoop(loop);\n" + 'window.D={P,vr,vrTick,vrAfterMove,update,set,setMode,generate,camera,THREE,scene,renderer,climbableAt,headBlocked,limbGround,cullTiles,get tiles(){return tiles},get limbHold(){return limbHold},get vrHandsObj(){return vrHandsObj},vrHands,zoomOverlay,poseHand,vrZoomRender,rockTop:(x,z)=>rockTopAt(x,z),input,get obstacles(){return obstacles},get H(){return H},groundAt,get state(){return state},set state(v){state=v},GRADE,setVR:v=>{VR_ON=v},VRUI,vruiOpen,vruiTick,vruiClose,startNew,beasts,updateAnimals,scatterBeasts,get world(){return world},loop:t=>loop(t),intro,levelQ,slopeNy,rockAround,tracers,updateGun,vrFire,GUN,get arms(){return arms},get WEAP(){return WEAP},get GUNSPOT(){return GUNSPOT},get ammoCans(){return ammoCans},get canMesh(){return canMesh},get FEAT(){return FEAT},get water(){return water},get mapDirty(){return mapDirty},zoomViewQ,setSeed:v=>{seed=v},get seed(){return seed},get STORM(){return STORM},stormTick:(dt,n)=>stormTick(dt,n),spawnStrike:n=>spawnStrike(n),get sunL(){return sunL},get hemi(){return hemi},get SUNB(){return SUNB},get weather(){return weather},get UW(){return UW},pickSpawn:p=>pickSpawn(p),okSpot:(x,z)=>okSpot(x,z),buildDiorama:()=>buildDiorama(),get MP(){return MP},mpHost:()=>mpHost(),mpJoin:c=>mpJoin(c),mpTick:dt=>mpTick(dt),mpSendStart:()=>mpSendStart(),mpHitTest:(a,b,c)=>mpHitTest(a,b,c),mpRelay:()=>mpRelay(),castShotDbg:(o,d,m)=>castShot(o,d,m),makeBullet:(...a)=>makeBullet(...a),get NADES(){return NADES},get nadeLoot(){return nadeLoot},get nadeArc(){return nadeArc},NADE,get squad(){return squad}, get zone(){return zone}, get CAPT(){return CAPT}, captTick:I=>captTick(I), zoneSeek:(z,e)=>zoneSeek(z,e), zoneSpawnInside:()=>zoneSpawnInside(), updateZone:dt=>updateZone(dt), drawMap:c=>drawMap(c),mpLocked:(p,w)=>mpLocked(p,w),get VRUIstage(){return VRUI.stage},pickSpawn2:p=>pickSpawn(p),vruiDropIn:()=>vruiDropIn(),renderSetup:()=>renderSetup(),get DROPS(){return DROPS},pvpSpill:()=>pvpSpill(),pvpLoadout:()=>pvpLoadout(),mpTakeHit:(d,h)=>mpTakeHit(d,h),get VHUD(){return VHUD},mpRoundOver:()=>mpRoundOver(),magOf:k=>magOf(k),tierOf:k=>tierOf(k),drawWheel:s=>drawWheel(s),pickGun:k=>pickGun(k),TIER,mpLeave:()=>mpLeave(),get VRUI(){return VRUI}};', 1)
assert "window.D=" in s and "window.FREEZE" in s, "hook points not found: update make_debug.py"
open(sys.argv[2], "w").write(s); print("wrote", sys.argv[2])
